### ISSUE TITLE
Crear método de selección : Boltzmann

### ISSUE THREAD

**Issue by florbest89** [florbest89/SIA-1C2016#25]

**Comment by florbest89** [comment]
Maria Cristina Parpaglione:
Selección de Boltzman. Dividan por la sumatoria y no por el promedio para que de valores entre 0 y 1.

Lo que se les ocurra, con sentido, lo pueden presentar si les está dando buenos resultados.

**Comment by mtsrvs** [comment]
Eso de la sumatoria ya esta. A cada uno le aplique la division que esta en las filminas. luego, como hago para seleccionar los individuos? Bueno, hice lo mismo que en ranking en esa parte. No esta explicado como en las filminas. Busque en internet y no encontre como hacer esa parte.
