### ISSUE TITLE
Crear método de selección : Ranking

### ISSUE THREAD

**Issue by florbest89** [florbest89/SIA-1C2016#29]

**Comment by mtsrvs** [comment]
para tenes una idea mejor de como implementarlo, encontre estos slides: [http://www.ia.urjc.es/cms/sites/default/files/userfiles/file/ia4/IA4_Sesion8_Geneticos_ppt.pdf](url)

**Comment by mtsrvs** [comment]
![screen shot 2016-06-18 at 12 59 48](https://cloud.githubusercontent.com/assets/2726530/16172007/c4ca82d6-3554-11e6-9127-b2b18812109d.png)
